import type { Metadata } from "next";
import "./globals.css";
import { poppins } from "@/app/ui/fonts";

import NavHeader from "@/app/ui/nav-header";

export const metadata: Metadata = {
    title: "Ōpōtiki App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html className={`${poppins.className} antialiased`} lang='en'>
            <body>
                <div className='main'>
                    <NavHeader />
                    {children}
                </div>
            </body>
        </html>
    );
}
